version: "5"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  springboot:
    image: marcioh/springboot:latest
    container_name: "springboot"
    ports:
      - 8080:8080
    links:
      - mongodb
      
      
      
      